language: python
python:
  - "2.6"
  - "2.7"
#before_install:
  # install NumPy dependencies
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq gfortran libatlas-base-dev
#  - sudo apt-get install -qq python-numpy
install:
  - pip install .
  - pip install -r requirements.txt
script:
#  - nosetests tests